<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Book" Member="Books">
    <Type Name="Book">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BWriter" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CategoryName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Category_Book" Member="Category" ThisKey="CId" OtherKey="Id" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Category_Book" Member="Books" ThisKey="Id" OtherKey="CId" Type="Book" />
    </Type>
  </Table>
  <Table Name="dbo.Question" Member="Questions">
    <Type Name="Question">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Question" Member="Question1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Question" Member="User" ThisKey="UId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Role" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="User_Question" Member="Questions" ThisKey="Id" OtherKey="UId" Type="Question" />
    </Type>
  </Table>
</Database>